name: Rust

on:
  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
      - "*.rs"
      - Cargo.lock
      - Cargo.toml

  pull_request:
    branches: [ "main" ]
    paths:
      - "*.rs"
      - Cargo.lock
      - Cargo.toml

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name:
        run: cargo install cargo-nextest --locked

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo nextest run